# Generated by Django 2.2.13 on 2020-08-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('expectedprice', models.IntegerField(blank=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='accounts.Fpo')),
            ],
        ),
    ]
